[build]
  command = "npm install"
  publish = "public"
  functions = "functions"

[build.environment]
  NODE_VERSION = "16"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200 